version: '3.8'

services:
  mariadb:
    image: mariadb:10.11
    container_name: mojave_db
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: mojave_bank
      MARIADB_USER: courier
      MARIADB_PASSWORD: newvegas
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data: